version: '3.8'

services:
  db:
    image: postgres:13
    container_name: petaniku_db
    environment:
      POSTGRES_USER: petaniku
      POSTGRES_PASSWORD: petaniku123
      POSTGRES_DB: petaniku
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petaniku -d petaniku"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: petaniku_backend
    ports:
      - "4001:4001"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: petaniku
      DB_PASSWORD: petaniku123
      DB_NAME: petaniku
      JWT_SECRET: paktanimangansayur
      JWT_EXPIRES_IN: 1h
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  pgdata:
  node_modules:
