const router = require("express").Router();
const { authenticateToken } = require("../middleware/auth");
const { authorize } = require("../middleware/roles");
const ctrl = require("../controllers/adminController");
router.use(authenticateToken, authorize("ADMIN"));
router.get("/users", ctrl.getUsers);
router.put("/users/:id", ctrl.updateUser);
router.delete("/users/:id", ctrl.deleteUser);
router.get("/products", ctrl.getProducts);
router.delete("/products/:id", ctrl.deleteProduct);
router.get("/reports", ctrl.getAllReports);
router.put("/reports/:id", ctrl.updateReport);
module.exports = router;
